version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: /
  exclude-paths: node_modules

cache:
    paths:
      - node_modules/**/*
