version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - src/**/*
    - dist/**/*
    - Procfile
    - public/**/*
  discard-paths: no
  base-directory: /

cache:
    paths:
      - node_modules/**/*
